---
- name: Remove the default Apache site configuration (000-default.conf)
  ansible.builtin.file:
    name: "{{ apache_sites_enabled }}/000-default.conf"
    state: absent

- name: Deploy openQA Apache configuration template
  ansible.builtin.template:
    src: openqa.conf.j2
    dest: "{{ apache_sites_available }}/openqa.conf"
    mode: "0644"
  notify: "Reload Apache"

- name: Enable the openQA Apache site by creating a symlink
  ansible.builtin.file:
    src: ../sites-available/openqa.conf
    dest: "{{ apache_sites_enabled }}/openqa.conf"
    state: link
  notify: "Reload Apache"

- name: Ensure Apache modules are enabled
  ansible.builtin.command: "a2enmod {{ item }}"
  changed_when: false
  loop: "{{ openqa_apache_modules }}"
  notify: "Reload Apache"
