openqa_common_packages:
  - acl
  - net-tools

openqa_packages:
  - openqa
  - openqa-client
  - openqa-doc
  - openqa-worker

openqa_postgresql_packages:
  - postgresql
  - postgresql-contrib
  - python3-psycopg2

openqa_db_name: openqa
openqa_db_user: openqa
openqa_db_password: "{{ vault_openqa_db_password | default('change_me') }}"

openqa_apache_modules:
  - headers
  - proxy
  - proxy_http
  - proxy_wstunnel
  - rewrite
  - expires

openqa_ini_file_path: /etc/openqa/openqa.ini
openqa_worker_ini_file_path: /etc/openqa/workers.ini
openqa_cache_dir_path: /var/lib/openqa/cache
