- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  listen: "Restart openqa services"

- name: Restart all openQA services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
  loop: >-
    {{
      ansible_facts['services'].values()
      | selectattr('name', 'search', '^openqa')
      | selectattr('state', '!=', 'unknown')
      |  map(attribute='name')
      | list
    }}
  when: ansible_facts.services is defined
  listen: "Restart openqa services"

- name: Reload Apache
  ansible.builtin.systemd_service:
    name: apache2
    state: reloaded
